SET(FLTK_CONFIG_SEARCH_PATH
  /usr/bin)

FIND_PROGRAM(FLTK_CONFIG  fltk-config  ${FLTK_CONFIG_SEARCH_PATH})

SET(FLTK_FOUND 1)
FOREACH(var FLTK_CONFIG)
  IF(NOT ${var})
	SET(FLTK_FOUND 0)
  ENDIF(NOT ${var})
ENDFOREACH(var)

IF(FLTK_FOUND)
  EXEC_PROGRAM(${FLTK_CONFIG} ARGS "--cxxflags" OUTPUT_VARIABLE FLTK_CFLAGS RETURN_VALUE RET)
  EXEC_PROGRAM(${FLTK_CONFIG} ARGS "--ldflags"  OUTPUT_VARIABLE FLTK_LFLAGS RETURN_VALUE RET)
ENDIF(FLTK_FOUND)
